# Site settings
title: DIAG
email: diag.dgist@gmail.com
url: https://diag.kr
description: "In the DGIST Intelligence Augmentation Group (DIAG), we do research in the intersection of HCI and AI. <br>We study and build hybrid intelligence systems &mdash; combining human and machine intelligence to understand and overcome challenging problems in AI."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: diag.kr

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: https://twitter.com/jeancrowdvision
#  - title: facebook
#    url:
#  - title: github
#    url:

# Build settings
markdown: kramdown
permalink: pretty
